In [2]:
import torch

In [10]:
!python -m spacy download en

     |████████████████████████████████| 12.0 MB 10.1 MB/s eta 0:00:01
✔ Download and installation successful
You can now load the model via spacy.load('en_core_web_sm')
✔ Linking successful
/Users/peng/MyProgram/venv_MLDL/lib/python3.8/site-packages/en_core_web_sm -->
/Users/peng/MyProgram/venv_MLDL/lib/python3.8/site-packages/spacy/data/en
You can now load the model via spacy.load('en')


In [11]:
from utils.data_reader import amazon_dataset_iters

In [12]:
dataset_folder = './data/Musical_Instruments_5/'

In [13]:
# Loading the dataset
text_vocab, tips_vocab, train_iter, val_iter, test_iter = (
    amazon_dataset_iters(dataset_folder)
)

Loading datasets...


/Users/peng/MyProgram/venv_MLDL/lib/python3.8/site-packages/torchtext/data/example.py:13: UserWarning: Example class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.
  warnings.warn('Example class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.', UserWarning)


datasets loaded
item vocab built
user vocab built
text vocab built
tips vocab built


/Users/peng/MyProgram/venv_MLDL/lib/python3.8/site-packages/torchtext/data/iterator.py:48: UserWarning: Iterator class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.
  warnings.warn('{} class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.'.format(self.__class__.__name__), UserWarning)


In [26]:
print(text_vocab.freqs['not'])
print(text_vocab.stoi['$start'])
print(train_iter)

4144
2


In [33]:
for train_iter_data in train_iter:
    print(train_iter_data)
    break


[torchtext.data.batch.Batch of size 32]
	[.item]:[torch.LongTensor of size 32]
	[.user]:[torch.LongTensor of size 32]
	[.text]:[torch.FloatTensor of size 32x19598]
	[.tips]:[torch.LongTensor of size 22x32]
	[.rating]:[torch.FloatTensor of size 32]


In [36]:
max([i.item.max().cpu().data.numpy() for i in train_iter] + [i.item.max().cpu().data.numpy() for i in test_iter])

array(608)

In [77]:
max([i.user.max().cpu().data.numpy() for i in train_iter] + [i.user.max().cpu().data.numpy() for i in test_iter])

array(1423)

In [80]:
int(max([i.user.max().cpu().data.numpy() for i in train_iter]))

1423

In [40]:
len(text_vocab.itos)

19598

In [41]:
len(tips_vocab.itos)

19598

In [47]:
for train_iter_data in train_iter:
    print(train_iter_data)
    print(train_iter_data.item)
    print(train_iter_data.tips)
    print(train_iter_data.tips[:-1])
    print(train_iter_data.tips[1:])
    break


[torchtext.data.batch.Batch of size 32]
	[.item]:[torch.LongTensor of size 32]
	[.user]:[torch.LongTensor of size 32]
	[.text]:[torch.FloatTensor of size 32x19598]
	[.tips]:[torch.LongTensor of size 22x32]
	[.rating]:[torch.FloatTensor of size 32]
tensor([163,  88, 525, 514,  20, 314,   3, 199, 376, 544,  19,  56, 205,  11,
        418, 458,  55, 143, 557, 112,   7,   6,  65, 133, 172, 256,  15, 486,
        158,  32,  35, 218])
tensor([[    2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
             2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
             2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
             2,     2],
        [  109,    47,  3925,   145,    73,    10,    29,   407,   217,    10,
           314,   302,    85,    35,    75,    54,   219,   132,    75,   379,
            77,    35,    75,  6603,   833,   207,   236,   352,   203,    29,
            29,     8],
        [   16,    10,     3,   195,  6334, 

In [44]:
len(train_iter)

225

In [48]:
for train_iter_data in train_iter:
    print(train_iter_data.tips.shape)
    print(train_iter_data.tips[:-1].shape)
    print(train_iter_data.tips[1:].shape)
    break

torch.Size([22, 32])
torch.Size([21, 32])
torch.Size([21, 32])


In [49]:
pad_token_id = 1
for train_iter_data in train_iter:
    print(train_iter_data.tips.shape)
    print(train_iter_data.tips[:-1].shape)
    print(train_iter_data.tips[1:].shape)
    pad_mask = ~(train_iter_data.tips[1:] == pad_token_id)
    print(pad_mask)
    break

torch.Size([22, 32])
torch.Size([21, 32])
torch.Size([21, 32])
tensor([[ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True, False,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         False,  True],
        [ True,  True,  True,  True,  True, False, False,  True,  True, False,
          True,  True,  True,  True, False,  True,  True,  True,  True,  Tr

In [57]:
tips_vocab.stoi['<pad>']

1

In [51]:
pad_token_id = 0
batch = torch.tensor([
    [1, 2, 0, 0],
    [4, 0, 0, 0],
    [3, 5, 6, 7]
])
pad_mask = ~(batch == pad_token_id)
print(pad_mask)
print(pad_mask.dtype)

tensor([[ True,  True, False, False],
        [ True, False, False, False],
        [ True,  True,  True,  True]])
torch.bool


In [58]:
import torch
import torch.nn as nn

In [71]:
loss = nn.MSELoss(reduction='sum')
input = torch.randn(5, requires_grad=True)
target = torch.randn(5)
output = loss(input, target)

In [72]:
output

tensor(10.7388, grad_fn=<MseLossBackward>)

In [73]:
input

tensor([-0.4051, -1.0110,  1.1901, -1.0760, -0.0908], requires_grad=True)

In [74]:
target

tensor([ 0.9078,  1.0293,  0.1894, -0.7429,  1.8431])

In [75]:
len(target)

5